export type AssetCategory = "Forex" | "Cripto" | "Ações" | "OTC";

export const ASSETS_CATALOG: Record<AssetCategory, string[]> = {
  Forex: [
    "AUDCAD","AUDCHF","AUDJPY","AUDNZD","AUDUSD","CADCHF","CADJPY","CHFJPY",
    "COPPER","EURAUD","EURCAD","EURCHF","EURGBP","EURJPY","EURNZD","EURUSD",
    "GBPAUD","GBPCAD","GBPCHF","GBPJPY","GBPNZD","GBPUSD","GOLD","NZDCAD",
    "NZDCHF","NZDJPY","NZDUSD","OIL_BRENT","SILVER","USDAUD","USDCAD","USDCHF",
    "USDJPY","XLMUSD",
  ],
  Cripto: [
    "ADAUSDT","ADAUSDTOTC","BNBUSDT","BNBUSDTOTC","BTCUSDT","BTCUSDTOTC",
    "DOGEUSDT","ETHOTC","ETHUSDT","LTCUSDT","LTCUSDTOTC","SOLOTC","SOLUSDT",
    "SUIUSDT","XRPUSDT",
  ],
  "Ações": [],
  OTC: [
    "AAPLOTC","AMZNOTC","AUDCHFOTC","AUDJPYOTC","AVAXOTC","CADCHFOTC","DISOTC",
    "DOGEOTC","EURAUDOTC","EURCADOTC","EURCHFOTC","EURGBPOTC","EURJPYOTC",
    "EURNZDOTC","EURUSDOTC","FBOTC","FORDOTC","GBPAUDOTC","GBPCHFOTC","GBPJPYOTC",
    "GOLDOTC","IBMOTC","INTCOTC","KOOTC","LINKOTC","MAOTC","MSFTOTC","NFLXOTC",
    "NIKEOTC","NVDAOTC","NZDJPYOTC","PYPLOTC","SBUXOTC","SPOTOTC","SUIOTC",
    "TSLAOTC","USDAUDOTC","USDBRLOTC","USDCHFOTC","VISAOTC","XAUUSDOTC","XPLOTC",
  ],
};

export const DEFAULT_PAYOUT = 1.85;