server {
    listen 80;
    server_name imperioinvestacademy.com www.imperioinvestacademy.com;

    root /var/www/imperioinvestacademy;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
