/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedTutorialRouteImport } from './routes/_authenticated/tutorial'
import { Route as AuthenticatedTelegramAccountsRouteImport } from './routes/_authenticated/telegram-accounts'
import { Route as AuthenticatedRecargaRouteImport } from './routes/_authenticated/recarga'
import { Route as AuthenticatedPremiumEmojisRouteImport } from './routes/_authenticated/premium-emojis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms.index'
import { Route as ApiPublicKirvanoWebhookRouteImport } from './routes/api/public/kirvano/webhook'
import { Route as ApiPublicCronDispatchRecurringRouteImport } from './routes/api/public/cron/dispatch-recurring'
import { Route as AuthenticatedRoomsRoomIdEditRouteImport } from './routes/_authenticated/rooms.$roomId.edit'
import { Route as ApiPublicTelegramWebhookAccountIdRouteImport } from './routes/api/public/telegram/webhook.$accountId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutorialRoute = AuthenticatedTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTelegramAccountsRoute =
  AuthenticatedTelegramAccountsRouteImport.update({
    id: '/telegram-accounts',
    path: '/telegram-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecargaRoute = AuthenticatedRecargaRouteImport.update({
  id: '/recarga',
  path: '/recarga',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumEmojisRoute =
  AuthenticatedPremiumEmojisRouteImport.update({
    id: '/premium-emojis',
    path: '/premium-emojis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicKirvanoWebhookRoute = ApiPublicKirvanoWebhookRouteImport.update({
  id: '/api/public/kirvano/webhook',
  path: '/api/public/kirvano/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDispatchRecurringRoute =
  ApiPublicCronDispatchRecurringRouteImport.update({
    id: '/api/public/cron/dispatch-recurring',
    path: '/api/public/cron/dispatch-recurring',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoomsRoomIdEditRoute =
  AuthenticatedRoomsRoomIdEditRouteImport.update({
    id: '/rooms/$roomId/edit',
    path: '/rooms/$roomId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTelegramWebhookAccountIdRoute =
  ApiPublicTelegramWebhookAccountIdRouteImport.update({
    id: '/api/public/telegram/webhook/$accountId',
    path: '/api/public/telegram/webhook/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premium-emojis': typeof AuthenticatedPremiumEmojisRoute
  '/recarga': typeof AuthenticatedRecargaRoute
  '/telegram-accounts': typeof AuthenticatedTelegramAccountsRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
  '/api/public/cron/dispatch-recurring': typeof ApiPublicCronDispatchRecurringRoute
  '/api/public/kirvano/webhook': typeof ApiPublicKirvanoWebhookRoute
  '/api/public/telegram/webhook/$accountId': typeof ApiPublicTelegramWebhookAccountIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premium-emojis': typeof AuthenticatedPremiumEmojisRoute
  '/recarga': typeof AuthenticatedRecargaRoute
  '/telegram-accounts': typeof AuthenticatedTelegramAccountsRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/': typeof AuthenticatedIndexRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
  '/api/public/cron/dispatch-recurring': typeof ApiPublicCronDispatchRecurringRoute
  '/api/public/kirvano/webhook': typeof ApiPublicKirvanoWebhookRoute
  '/api/public/telegram/webhook/$accountId': typeof ApiPublicTelegramWebhookAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/premium-emojis': typeof AuthenticatedPremiumEmojisRoute
  '/_authenticated/recarga': typeof AuthenticatedRecargaRoute
  '/_authenticated/telegram-accounts': typeof AuthenticatedTelegramAccountsRoute
  '/_authenticated/tutorial': typeof AuthenticatedTutorialRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
  '/api/public/cron/dispatch-recurring': typeof ApiPublicCronDispatchRecurringRoute
  '/api/public/kirvano/webhook': typeof ApiPublicKirvanoWebhookRoute
  '/api/public/telegram/webhook/$accountId': typeof ApiPublicTelegramWebhookAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/membros'
    | '/mensagens'
    | '/perfil'
    | '/premium-emojis'
    | '/recarga'
    | '/telegram-accounts'
    | '/tutorial'
    | '/videos'
    | '/rooms/'
    | '/rooms/$roomId/edit'
    | '/api/public/cron/dispatch-recurring'
    | '/api/public/kirvano/webhook'
    | '/api/public/telegram/webhook/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/membros'
    | '/mensagens'
    | '/perfil'
    | '/premium-emojis'
    | '/recarga'
    | '/telegram-accounts'
    | '/tutorial'
    | '/videos'
    | '/'
    | '/rooms'
    | '/rooms/$roomId/edit'
    | '/api/public/cron/dispatch-recurring'
    | '/api/public/kirvano/webhook'
    | '/api/public/telegram/webhook/$accountId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/membros'
    | '/_authenticated/mensagens'
    | '/_authenticated/perfil'
    | '/_authenticated/premium-emojis'
    | '/_authenticated/recarga'
    | '/_authenticated/telegram-accounts'
    | '/_authenticated/tutorial'
    | '/_authenticated/videos'
    | '/_authenticated/'
    | '/_authenticated/rooms/'
    | '/_authenticated/rooms/$roomId/edit'
    | '/api/public/cron/dispatch-recurring'
    | '/api/public/kirvano/webhook'
    | '/api/public/telegram/webhook/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCronDispatchRecurringRoute: typeof ApiPublicCronDispatchRecurringRoute
  ApiPublicKirvanoWebhookRoute: typeof ApiPublicKirvanoWebhookRoute
  ApiPublicTelegramWebhookAccountIdRoute: typeof ApiPublicTelegramWebhookAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutorial': {
      id: '/_authenticated/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AuthenticatedTutorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telegram-accounts': {
      id: '/_authenticated/telegram-accounts'
      path: '/telegram-accounts'
      fullPath: '/telegram-accounts'
      preLoaderRoute: typeof AuthenticatedTelegramAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recarga': {
      id: '/_authenticated/recarga'
      path: '/recarga'
      fullPath: '/recarga'
      preLoaderRoute: typeof AuthenticatedRecargaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium-emojis': {
      id: '/_authenticated/premium-emojis'
      path: '/premium-emojis'
      fullPath: '/premium-emojis'
      preLoaderRoute: typeof AuthenticatedPremiumEmojisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/kirvano/webhook': {
      id: '/api/public/kirvano/webhook'
      path: '/api/public/kirvano/webhook'
      fullPath: '/api/public/kirvano/webhook'
      preLoaderRoute: typeof ApiPublicKirvanoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-recurring': {
      id: '/api/public/cron/dispatch-recurring'
      path: '/api/public/cron/dispatch-recurring'
      fullPath: '/api/public/cron/dispatch-recurring'
      preLoaderRoute: typeof ApiPublicCronDispatchRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/$roomId/edit': {
      id: '/_authenticated/rooms/$roomId/edit'
      path: '/rooms/$roomId/edit'
      fullPath: '/rooms/$roomId/edit'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/telegram/webhook/$accountId': {
      id: '/api/public/telegram/webhook/$accountId'
      path: '/api/public/telegram/webhook/$accountId'
      fullPath: '/api/public/telegram/webhook/$accountId'
      preLoaderRoute: typeof ApiPublicTelegramWebhookAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPremiumEmojisRoute: typeof AuthenticatedPremiumEmojisRoute
  AuthenticatedRecargaRoute: typeof AuthenticatedRecargaRoute
  AuthenticatedTelegramAccountsRoute: typeof AuthenticatedTelegramAccountsRoute
  AuthenticatedTutorialRoute: typeof AuthenticatedTutorialRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedRoomsRoomIdEditRoute: typeof AuthenticatedRoomsRoomIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPremiumEmojisRoute: AuthenticatedPremiumEmojisRoute,
  AuthenticatedRecargaRoute: AuthenticatedRecargaRoute,
  AuthenticatedTelegramAccountsRoute: AuthenticatedTelegramAccountsRoute,
  AuthenticatedTutorialRoute: AuthenticatedTutorialRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
  AuthenticatedRoomsRoomIdEditRoute: AuthenticatedRoomsRoomIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicCronDispatchRecurringRoute: ApiPublicCronDispatchRecurringRoute,
  ApiPublicKirvanoWebhookRoute: ApiPublicKirvanoWebhookRoute,
  ApiPublicTelegramWebhookAccountIdRoute:
    ApiPublicTelegramWebhookAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
