/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedTutorialRouteImport } from './routes/_authenticated/tutorial'
import { Route as AuthenticatedTelegramAccountsRouteImport } from './routes/_authenticated/telegram-accounts'
import { Route as AuthenticatedRecargaRouteImport } from './routes/_authenticated/recarga'
import { Route as AuthenticatedPremiumEmojisRouteImport } from './routes/_authenticated/premium-emojis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTrackeamentoIndexRouteImport } from './routes/_authenticated/trackeamento.index'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms.index'
import { Route as AuthenticatedTrackeamentoPixelsRouteImport } from './routes/_authenticated/trackeamento.pixels'
import { Route as AuthenticatedTrackeamentoDominiosRouteImport } from './routes/_authenticated/trackeamento.dominios'
import { Route as AuthenticatedTrackeamentoPixelIdRouteImport } from './routes/_authenticated/trackeamento.$pixelId'
import { Route as AuthenticatedIntegracoesMetaRouteImport } from './routes/_authenticated/integracoes.meta'
import { Route as AuthenticatedBotsLogsRouteImport } from './routes/_authenticated/bots.logs'
import { Route as AuthenticatedBotsEncaminhadorRouteImport } from './routes/_authenticated/bots.encaminhador'
import { Route as AuthenticatedBotsBoasvindasRouteImport } from './routes/_authenticated/bots.boasvindas'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track/click'
import { Route as ApiPublicKirvanoWebhookRouteImport } from './routes/api/public/kirvano/webhook'
import { Route as ApiPublicCronDispatchSignalsRouteImport } from './routes/api/public/cron/dispatch-signals'
import { Route as ApiPublicCronDispatchSessionsRouteImport } from './routes/api/public/cron/dispatch-sessions'
import { Route as ApiPublicCronDispatchRecurringRouteImport } from './routes/api/public/cron/dispatch-recurring'
import { Route as ApiPublicCronDispatchMarketTipsRouteImport } from './routes/api/public/cron/dispatch-market-tips'
import { Route as AuthenticatedRoomsRoomIdEditRouteImport } from './routes/_authenticated/rooms.$roomId.edit'
import { Route as ApiPublicTrackPostbackPixelIdRouteImport } from './routes/api/public/track/postback.$pixelId'
import { Route as ApiPublicTelegramWebhookAccountIdRouteImport } from './routes/api/public/telegram/webhook.$accountId'
import { Route as ApiPublicTrackGClickIdOfferSlugRouteImport } from './routes/api/public/track/g.$clickId.$offerSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutorialRoute = AuthenticatedTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTelegramAccountsRoute =
  AuthenticatedTelegramAccountsRouteImport.update({
    id: '/telegram-accounts',
    path: '/telegram-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecargaRoute = AuthenticatedRecargaRouteImport.update({
  id: '/recarga',
  path: '/recarga',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumEmojisRoute =
  AuthenticatedPremiumEmojisRouteImport.update({
    id: '/premium-emojis',
    path: '/premium-emojis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackeamentoIndexRoute =
  AuthenticatedTrackeamentoIndexRouteImport.update({
    id: '/trackeamento/',
    path: '/trackeamento/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackeamentoPixelsRoute =
  AuthenticatedTrackeamentoPixelsRouteImport.update({
    id: '/trackeamento/pixels',
    path: '/trackeamento/pixels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackeamentoDominiosRoute =
  AuthenticatedTrackeamentoDominiosRouteImport.update({
    id: '/trackeamento/dominios',
    path: '/trackeamento/dominios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackeamentoPixelIdRoute =
  AuthenticatedTrackeamentoPixelIdRouteImport.update({
    id: '/trackeamento/$pixelId',
    path: '/trackeamento/$pixelId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegracoesMetaRoute =
  AuthenticatedIntegracoesMetaRouteImport.update({
    id: '/integracoes/meta',
    path: '/integracoes/meta',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBotsLogsRoute = AuthenticatedBotsLogsRouteImport.update({
  id: '/bots/logs',
  path: '/bots/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBotsEncaminhadorRoute =
  AuthenticatedBotsEncaminhadorRouteImport.update({
    id: '/bots/encaminhador',
    path: '/bots/encaminhador',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBotsBoasvindasRoute =
  AuthenticatedBotsBoasvindasRouteImport.update({
    id: '/bots/boasvindas',
    path: '/bots/boasvindas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track/click',
  path: '/api/public/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKirvanoWebhookRoute = ApiPublicKirvanoWebhookRouteImport.update({
  id: '/api/public/kirvano/webhook',
  path: '/api/public/kirvano/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDispatchSignalsRoute =
  ApiPublicCronDispatchSignalsRouteImport.update({
    id: '/api/public/cron/dispatch-signals',
    path: '/api/public/cron/dispatch-signals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDispatchSessionsRoute =
  ApiPublicCronDispatchSessionsRouteImport.update({
    id: '/api/public/cron/dispatch-sessions',
    path: '/api/public/cron/dispatch-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDispatchRecurringRoute =
  ApiPublicCronDispatchRecurringRouteImport.update({
    id: '/api/public/cron/dispatch-recurring',
    path: '/api/public/cron/dispatch-recurring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDispatchMarketTipsRoute =
  ApiPublicCronDispatchMarketTipsRouteImport.update({
    id: '/api/public/cron/dispatch-market-tips',
    path: '/api/public/cron/dispatch-market-tips',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoomsRoomIdEditRoute =
  AuthenticatedRoomsRoomIdEditRouteImport.update({
    id: '/rooms/$roomId/edit',
    path: '/rooms/$roomId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTrackPostbackPixelIdRoute =
  ApiPublicTrackPostbackPixelIdRouteImport.update({
    id: '/api/public/track/postback/$pixelId',
    path: '/api/public/track/postback/$pixelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookAccountIdRoute =
  ApiPublicTelegramWebhookAccountIdRouteImport.update({
    id: '/api/public/telegram/webhook/$accountId',
    path: '/api/public/telegram/webhook/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackGClickIdOfferSlugRoute =
  ApiPublicTrackGClickIdOfferSlugRouteImport.update({
    id: '/api/public/track/g/$clickId/$offerSlug',
    path: '/api/public/track/g/$clickId/$offerSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premium-emojis': typeof AuthenticatedPremiumEmojisRoute
  '/recarga': typeof AuthenticatedRecargaRoute
  '/telegram-accounts': typeof AuthenticatedTelegramAccountsRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/bots/boasvindas': typeof AuthenticatedBotsBoasvindasRoute
  '/bots/encaminhador': typeof AuthenticatedBotsEncaminhadorRoute
  '/bots/logs': typeof AuthenticatedBotsLogsRoute
  '/integracoes/meta': typeof AuthenticatedIntegracoesMetaRoute
  '/trackeamento/$pixelId': typeof AuthenticatedTrackeamentoPixelIdRoute
  '/trackeamento/dominios': typeof AuthenticatedTrackeamentoDominiosRoute
  '/trackeamento/pixels': typeof AuthenticatedTrackeamentoPixelsRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/trackeamento/': typeof AuthenticatedTrackeamentoIndexRoute
  '/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
  '/api/public/cron/dispatch-market-tips': typeof ApiPublicCronDispatchMarketTipsRoute
  '/api/public/cron/dispatch-recurring': typeof ApiPublicCronDispatchRecurringRoute
  '/api/public/cron/dispatch-sessions': typeof ApiPublicCronDispatchSessionsRoute
  '/api/public/cron/dispatch-signals': typeof ApiPublicCronDispatchSignalsRoute
  '/api/public/kirvano/webhook': typeof ApiPublicKirvanoWebhookRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/telegram/webhook/$accountId': typeof ApiPublicTelegramWebhookAccountIdRoute
  '/api/public/track/postback/$pixelId': typeof ApiPublicTrackPostbackPixelIdRoute
  '/api/public/track/g/$clickId/$offerSlug': typeof ApiPublicTrackGClickIdOfferSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/premium-emojis': typeof AuthenticatedPremiumEmojisRoute
  '/recarga': typeof AuthenticatedRecargaRoute
  '/telegram-accounts': typeof AuthenticatedTelegramAccountsRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/': typeof AuthenticatedIndexRoute
  '/bots/boasvindas': typeof AuthenticatedBotsBoasvindasRoute
  '/bots/encaminhador': typeof AuthenticatedBotsEncaminhadorRoute
  '/bots/logs': typeof AuthenticatedBotsLogsRoute
  '/integracoes/meta': typeof AuthenticatedIntegracoesMetaRoute
  '/trackeamento/$pixelId': typeof AuthenticatedTrackeamentoPixelIdRoute
  '/trackeamento/dominios': typeof AuthenticatedTrackeamentoDominiosRoute
  '/trackeamento/pixels': typeof AuthenticatedTrackeamentoPixelsRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/trackeamento': typeof AuthenticatedTrackeamentoIndexRoute
  '/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
  '/api/public/cron/dispatch-market-tips': typeof ApiPublicCronDispatchMarketTipsRoute
  '/api/public/cron/dispatch-recurring': typeof ApiPublicCronDispatchRecurringRoute
  '/api/public/cron/dispatch-sessions': typeof ApiPublicCronDispatchSessionsRoute
  '/api/public/cron/dispatch-signals': typeof ApiPublicCronDispatchSignalsRoute
  '/api/public/kirvano/webhook': typeof ApiPublicKirvanoWebhookRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/telegram/webhook/$accountId': typeof ApiPublicTelegramWebhookAccountIdRoute
  '/api/public/track/postback/$pixelId': typeof ApiPublicTrackPostbackPixelIdRoute
  '/api/public/track/g/$clickId/$offerSlug': typeof ApiPublicTrackGClickIdOfferSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/premium-emojis': typeof AuthenticatedPremiumEmojisRoute
  '/_authenticated/recarga': typeof AuthenticatedRecargaRoute
  '/_authenticated/telegram-accounts': typeof AuthenticatedTelegramAccountsRoute
  '/_authenticated/tutorial': typeof AuthenticatedTutorialRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bots/boasvindas': typeof AuthenticatedBotsBoasvindasRoute
  '/_authenticated/bots/encaminhador': typeof AuthenticatedBotsEncaminhadorRoute
  '/_authenticated/bots/logs': typeof AuthenticatedBotsLogsRoute
  '/_authenticated/integracoes/meta': typeof AuthenticatedIntegracoesMetaRoute
  '/_authenticated/trackeamento/$pixelId': typeof AuthenticatedTrackeamentoPixelIdRoute
  '/_authenticated/trackeamento/dominios': typeof AuthenticatedTrackeamentoDominiosRoute
  '/_authenticated/trackeamento/pixels': typeof AuthenticatedTrackeamentoPixelsRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/trackeamento/': typeof AuthenticatedTrackeamentoIndexRoute
  '/_authenticated/rooms/$roomId/edit': typeof AuthenticatedRoomsRoomIdEditRoute
  '/api/public/cron/dispatch-market-tips': typeof ApiPublicCronDispatchMarketTipsRoute
  '/api/public/cron/dispatch-recurring': typeof ApiPublicCronDispatchRecurringRoute
  '/api/public/cron/dispatch-sessions': typeof ApiPublicCronDispatchSessionsRoute
  '/api/public/cron/dispatch-signals': typeof ApiPublicCronDispatchSignalsRoute
  '/api/public/kirvano/webhook': typeof ApiPublicKirvanoWebhookRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/telegram/webhook/$accountId': typeof ApiPublicTelegramWebhookAccountIdRoute
  '/api/public/track/postback/$pixelId': typeof ApiPublicTrackPostbackPixelIdRoute
  '/api/public/track/g/$clickId/$offerSlug': typeof ApiPublicTrackGClickIdOfferSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/membros'
    | '/mensagens'
    | '/perfil'
    | '/premium-emojis'
    | '/recarga'
    | '/telegram-accounts'
    | '/tutorial'
    | '/videos'
    | '/bots/boasvindas'
    | '/bots/encaminhador'
    | '/bots/logs'
    | '/integracoes/meta'
    | '/trackeamento/$pixelId'
    | '/trackeamento/dominios'
    | '/trackeamento/pixels'
    | '/rooms/'
    | '/trackeamento/'
    | '/rooms/$roomId/edit'
    | '/api/public/cron/dispatch-market-tips'
    | '/api/public/cron/dispatch-recurring'
    | '/api/public/cron/dispatch-sessions'
    | '/api/public/cron/dispatch-signals'
    | '/api/public/kirvano/webhook'
    | '/api/public/track/click'
    | '/api/public/telegram/webhook/$accountId'
    | '/api/public/track/postback/$pixelId'
    | '/api/public/track/g/$clickId/$offerSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/membros'
    | '/mensagens'
    | '/perfil'
    | '/premium-emojis'
    | '/recarga'
    | '/telegram-accounts'
    | '/tutorial'
    | '/videos'
    | '/'
    | '/bots/boasvindas'
    | '/bots/encaminhador'
    | '/bots/logs'
    | '/integracoes/meta'
    | '/trackeamento/$pixelId'
    | '/trackeamento/dominios'
    | '/trackeamento/pixels'
    | '/rooms'
    | '/trackeamento'
    | '/rooms/$roomId/edit'
    | '/api/public/cron/dispatch-market-tips'
    | '/api/public/cron/dispatch-recurring'
    | '/api/public/cron/dispatch-sessions'
    | '/api/public/cron/dispatch-signals'
    | '/api/public/kirvano/webhook'
    | '/api/public/track/click'
    | '/api/public/telegram/webhook/$accountId'
    | '/api/public/track/postback/$pixelId'
    | '/api/public/track/g/$clickId/$offerSlug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/membros'
    | '/_authenticated/mensagens'
    | '/_authenticated/perfil'
    | '/_authenticated/premium-emojis'
    | '/_authenticated/recarga'
    | '/_authenticated/telegram-accounts'
    | '/_authenticated/tutorial'
    | '/_authenticated/videos'
    | '/_authenticated/'
    | '/_authenticated/bots/boasvindas'
    | '/_authenticated/bots/encaminhador'
    | '/_authenticated/bots/logs'
    | '/_authenticated/integracoes/meta'
    | '/_authenticated/trackeamento/$pixelId'
    | '/_authenticated/trackeamento/dominios'
    | '/_authenticated/trackeamento/pixels'
    | '/_authenticated/rooms/'
    | '/_authenticated/trackeamento/'
    | '/_authenticated/rooms/$roomId/edit'
    | '/api/public/cron/dispatch-market-tips'
    | '/api/public/cron/dispatch-recurring'
    | '/api/public/cron/dispatch-sessions'
    | '/api/public/cron/dispatch-signals'
    | '/api/public/kirvano/webhook'
    | '/api/public/track/click'
    | '/api/public/telegram/webhook/$accountId'
    | '/api/public/track/postback/$pixelId'
    | '/api/public/track/g/$clickId/$offerSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCronDispatchMarketTipsRoute: typeof ApiPublicCronDispatchMarketTipsRoute
  ApiPublicCronDispatchRecurringRoute: typeof ApiPublicCronDispatchRecurringRoute
  ApiPublicCronDispatchSessionsRoute: typeof ApiPublicCronDispatchSessionsRoute
  ApiPublicCronDispatchSignalsRoute: typeof ApiPublicCronDispatchSignalsRoute
  ApiPublicKirvanoWebhookRoute: typeof ApiPublicKirvanoWebhookRoute
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  ApiPublicTelegramWebhookAccountIdRoute: typeof ApiPublicTelegramWebhookAccountIdRoute
  ApiPublicTrackPostbackPixelIdRoute: typeof ApiPublicTrackPostbackPixelIdRoute
  ApiPublicTrackGClickIdOfferSlugRoute: typeof ApiPublicTrackGClickIdOfferSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tutorial': {
      id: '/_authenticated/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AuthenticatedTutorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telegram-accounts': {
      id: '/_authenticated/telegram-accounts'
      path: '/telegram-accounts'
      fullPath: '/telegram-accounts'
      preLoaderRoute: typeof AuthenticatedTelegramAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recarga': {
      id: '/_authenticated/recarga'
      path: '/recarga'
      fullPath: '/recarga'
      preLoaderRoute: typeof AuthenticatedRecargaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium-emojis': {
      id: '/_authenticated/premium-emojis'
      path: '/premium-emojis'
      fullPath: '/premium-emojis'
      preLoaderRoute: typeof AuthenticatedPremiumEmojisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackeamento/': {
      id: '/_authenticated/trackeamento/'
      path: '/trackeamento'
      fullPath: '/trackeamento/'
      preLoaderRoute: typeof AuthenticatedTrackeamentoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackeamento/pixels': {
      id: '/_authenticated/trackeamento/pixels'
      path: '/trackeamento/pixels'
      fullPath: '/trackeamento/pixels'
      preLoaderRoute: typeof AuthenticatedTrackeamentoPixelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackeamento/dominios': {
      id: '/_authenticated/trackeamento/dominios'
      path: '/trackeamento/dominios'
      fullPath: '/trackeamento/dominios'
      preLoaderRoute: typeof AuthenticatedTrackeamentoDominiosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackeamento/$pixelId': {
      id: '/_authenticated/trackeamento/$pixelId'
      path: '/trackeamento/$pixelId'
      fullPath: '/trackeamento/$pixelId'
      preLoaderRoute: typeof AuthenticatedTrackeamentoPixelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes/meta': {
      id: '/_authenticated/integracoes/meta'
      path: '/integracoes/meta'
      fullPath: '/integracoes/meta'
      preLoaderRoute: typeof AuthenticatedIntegracoesMetaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots/logs': {
      id: '/_authenticated/bots/logs'
      path: '/bots/logs'
      fullPath: '/bots/logs'
      preLoaderRoute: typeof AuthenticatedBotsLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots/encaminhador': {
      id: '/_authenticated/bots/encaminhador'
      path: '/bots/encaminhador'
      fullPath: '/bots/encaminhador'
      preLoaderRoute: typeof AuthenticatedBotsEncaminhadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots/boasvindas': {
      id: '/_authenticated/bots/boasvindas'
      path: '/bots/boasvindas'
      fullPath: '/bots/boasvindas'
      preLoaderRoute: typeof AuthenticatedBotsBoasvindasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/track/click': {
      id: '/api/public/track/click'
      path: '/api/public/track/click'
      fullPath: '/api/public/track/click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kirvano/webhook': {
      id: '/api/public/kirvano/webhook'
      path: '/api/public/kirvano/webhook'
      fullPath: '/api/public/kirvano/webhook'
      preLoaderRoute: typeof ApiPublicKirvanoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-signals': {
      id: '/api/public/cron/dispatch-signals'
      path: '/api/public/cron/dispatch-signals'
      fullPath: '/api/public/cron/dispatch-signals'
      preLoaderRoute: typeof ApiPublicCronDispatchSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-sessions': {
      id: '/api/public/cron/dispatch-sessions'
      path: '/api/public/cron/dispatch-sessions'
      fullPath: '/api/public/cron/dispatch-sessions'
      preLoaderRoute: typeof ApiPublicCronDispatchSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-recurring': {
      id: '/api/public/cron/dispatch-recurring'
      path: '/api/public/cron/dispatch-recurring'
      fullPath: '/api/public/cron/dispatch-recurring'
      preLoaderRoute: typeof ApiPublicCronDispatchRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-market-tips': {
      id: '/api/public/cron/dispatch-market-tips'
      path: '/api/public/cron/dispatch-market-tips'
      fullPath: '/api/public/cron/dispatch-market-tips'
      preLoaderRoute: typeof ApiPublicCronDispatchMarketTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/$roomId/edit': {
      id: '/_authenticated/rooms/$roomId/edit'
      path: '/rooms/$roomId/edit'
      fullPath: '/rooms/$roomId/edit'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/track/postback/$pixelId': {
      id: '/api/public/track/postback/$pixelId'
      path: '/api/public/track/postback/$pixelId'
      fullPath: '/api/public/track/postback/$pixelId'
      preLoaderRoute: typeof ApiPublicTrackPostbackPixelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook/$accountId': {
      id: '/api/public/telegram/webhook/$accountId'
      path: '/api/public/telegram/webhook/$accountId'
      fullPath: '/api/public/telegram/webhook/$accountId'
      preLoaderRoute: typeof ApiPublicTelegramWebhookAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/g/$clickId/$offerSlug': {
      id: '/api/public/track/g/$clickId/$offerSlug'
      path: '/api/public/track/g/$clickId/$offerSlug'
      fullPath: '/api/public/track/g/$clickId/$offerSlug'
      preLoaderRoute: typeof ApiPublicTrackGClickIdOfferSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPremiumEmojisRoute: typeof AuthenticatedPremiumEmojisRoute
  AuthenticatedRecargaRoute: typeof AuthenticatedRecargaRoute
  AuthenticatedTelegramAccountsRoute: typeof AuthenticatedTelegramAccountsRoute
  AuthenticatedTutorialRoute: typeof AuthenticatedTutorialRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBotsBoasvindasRoute: typeof AuthenticatedBotsBoasvindasRoute
  AuthenticatedBotsEncaminhadorRoute: typeof AuthenticatedBotsEncaminhadorRoute
  AuthenticatedBotsLogsRoute: typeof AuthenticatedBotsLogsRoute
  AuthenticatedIntegracoesMetaRoute: typeof AuthenticatedIntegracoesMetaRoute
  AuthenticatedTrackeamentoPixelIdRoute: typeof AuthenticatedTrackeamentoPixelIdRoute
  AuthenticatedTrackeamentoDominiosRoute: typeof AuthenticatedTrackeamentoDominiosRoute
  AuthenticatedTrackeamentoPixelsRoute: typeof AuthenticatedTrackeamentoPixelsRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedTrackeamentoIndexRoute: typeof AuthenticatedTrackeamentoIndexRoute
  AuthenticatedRoomsRoomIdEditRoute: typeof AuthenticatedRoomsRoomIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPremiumEmojisRoute: AuthenticatedPremiumEmojisRoute,
  AuthenticatedRecargaRoute: AuthenticatedRecargaRoute,
  AuthenticatedTelegramAccountsRoute: AuthenticatedTelegramAccountsRoute,
  AuthenticatedTutorialRoute: AuthenticatedTutorialRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBotsBoasvindasRoute: AuthenticatedBotsBoasvindasRoute,
  AuthenticatedBotsEncaminhadorRoute: AuthenticatedBotsEncaminhadorRoute,
  AuthenticatedBotsLogsRoute: AuthenticatedBotsLogsRoute,
  AuthenticatedIntegracoesMetaRoute: AuthenticatedIntegracoesMetaRoute,
  AuthenticatedTrackeamentoPixelIdRoute: AuthenticatedTrackeamentoPixelIdRoute,
  AuthenticatedTrackeamentoDominiosRoute:
    AuthenticatedTrackeamentoDominiosRoute,
  AuthenticatedTrackeamentoPixelsRoute: AuthenticatedTrackeamentoPixelsRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
  AuthenticatedTrackeamentoIndexRoute: AuthenticatedTrackeamentoIndexRoute,
  AuthenticatedRoomsRoomIdEditRoute: AuthenticatedRoomsRoomIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicCronDispatchMarketTipsRoute: ApiPublicCronDispatchMarketTipsRoute,
  ApiPublicCronDispatchRecurringRoute: ApiPublicCronDispatchRecurringRoute,
  ApiPublicCronDispatchSessionsRoute: ApiPublicCronDispatchSessionsRoute,
  ApiPublicCronDispatchSignalsRoute: ApiPublicCronDispatchSignalsRoute,
  ApiPublicKirvanoWebhookRoute: ApiPublicKirvanoWebhookRoute,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  ApiPublicTelegramWebhookAccountIdRoute:
    ApiPublicTelegramWebhookAccountIdRoute,
  ApiPublicTrackPostbackPixelIdRoute: ApiPublicTrackPostbackPixelIdRoute,
  ApiPublicTrackGClickIdOfferSlugRoute: ApiPublicTrackGClickIdOfferSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
