REVOKE EXECUTE ON FUNCTION public.tracking_attribution(UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.tracking_attribution(UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM anon;
REVOKE EXECUTE ON FUNCTION public.tracking_attribution(UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM authenticated;